### ISSUE TITLE
Make braille utils OSGi compatible

### ISSUE THREAD

**Issue by GoogleCodeExporter** [joeha480/brailleutils#47]
```
Add OSGi support for braille utils
```

Original issue reported on code.google.com by `joel.hak...@mtm.se` on 18 Jan 2013 at 8:35
* Blocking: #18

**Comment by bertfrees** [comment]
@joeha480 What is left to be done to enable OSGi?

**Comment by joeha480** [comment]
As far as I know, what's left is mostly structural. The API package should perhaps be cleaner and not contain that much code. Perhaps some OSGi tests would be good too.

**Comment by bertfrees** [comment]
Okay. So if the Declarative Services XML files were generated it would probably work? I could help you with the OSGi tests.
