### ISSUE TITLE
Add Braillo table that maps characters in ranges [60..7E] and [40..5E] to same braille

### ISSUE THREAD

**Issue by bertfrees** [joeha480/brailleutils#60]
Ignoring case is already supported.

See https://github.com/snaekobbi/requirements/pull/2#issuecomment-117500338

**Comment by joeha480** [comment]
Is this for a particular Braillo table or a particular Braillo model?

**Comment by bertfrees** [comment]
Celia use Braillo 200 with the BRAILLO-6-us-001-00 table.

**Comment by joeha480** [comment]
Seems safe to update that table if there should only be additional characters in the text to braille conversion.

**Comment by bertfrees** [comment]
Yes think so too.
